# Generated by Django 2.2.3 on 2019-07-11 09:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='images/category/', verbose_name='تصویر دوره')),
            ],
        ),
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='images/cources/', verbose_name='تصویر دوره')),
                ('content', models.TextField(verbose_name='درباره دوره')),
                ('teacher', models.CharField(max_length=200, verbose_name='نام مدرس')),
                ('time', models.CharField(max_length=340, verbose_name='مدت دوره')),
                ('school', models.CharField(max_length=290, verbose_name='نام آموزشگاه')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس آموزشگاه')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='هزینه دوره')),
                ('date', models.DateField(default=datetime.date(2019, 7, 11), verbose_name='تاریخ')),
                ('date_start', models.DateField(verbose_name=' تاریخ شروع دوره')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cources.Category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
        ),
    ]
